Fliplet/fliplet-widget-notification-inbox

css/build.css
js/build.js
js/build.templates.js
js/libs.js
templates/notifications.toolbar.build.hbs
templates/toolbar.build.hbs
templates/toolbar.empty.build.hbs

- Adds UI to view push notification subscription ID and subscribe to push notifications
- Adds analytics event tracking [as outlined here](https://docs.google.com/spreadsheets/d/1Ni2KLq4vIVcxxvjOZpTo5q6JPk-1aehZu8jjRJ8NaBA/edit#gid=1226294949)

Updates to notification inbox

---

js/interface.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/3855

Ensures Notification Inbox interface can be closed

---

js/build.templates.js
js/libs.js
templates/notification.build.hbs

Ref. https://github.com/Fliplet/fliplet-studio/issues/4166

Order notifications by orderAt date

---

css/build.css

Ref. https://github.com/Fliplet/fliplet-studio/issues/4245

RTL support for toolbar

---

css/build.css
js/build.templates.js
js/libs.js
templates/newNotifications.build.hbs
templates/toolbar.build.hbs
templates/toolbar.empty.build.hbs

Ref. https://github.com/Fliplet/fliplet-studio/issues/5053

Adds refresh icon to notification inbox

---

js/build.js
js/libs.js

requires https://github.com/Fliplet/fliplet-widget-notifications/pull/6

refactor to allow better init

---

css/build.css
js/build.templates.js
js/libs.js
templates/notification.build.hbs

Also adds a link icon to linked notifications.

Updates inbox UI to match LFD look and feel

---

css/interface.css
interface.html
js/build.js
js/interface.js
js/libs.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/5948
Studio Interface
Sample notifications in inbox

Make demo mode optional via widget interface

---

js/libs.js

Follows https://github.com/Fliplet/fliplet-widget-notification-inbox/pull/15

Don't initiate demo mode when notification inbox is empty

---

.gitignore
css/app/build.css
js/app/build.js
js/app/libs.js
js/build.js
js/interface.js
widget.json

ref https://github.com/Fliplet/fliplet-studio/issues/6336

[Maintenance] Moves app notification component code into notifications inbox

---

js/build.js
js/libs.js

Ref. https://weboo.atlassian.net/browse/ID-470

ID-470 [Fix] Ignore demo mode for live apps

---

js/build.js
widget.json

ID-784 [Feat] Save last seen timestamp

---

js/app/build.js
js/app/libs.js
js/build.js
js/libs.js

Requires https://github.com/Fliplet/fliplet-api/pull/4566

ID-810 [Feat] Keep app and menu badge number sync-ed according to app settings

---

js/app/libs.js

ID-810 [Feat] Check the latest notification counts when app resumes

---

js/app/build.js
js/app/libs.js
js/build.js
js/libs.js

`Fliplet.Widget.get('AppNotifications')` and `Fliplet.Widget.get('NotificationInbox')` contain a variety of functions for testing and custom triggers.

ID-810 [Feat] Add access to widget JS APIs

---

js/app/libs.js

ID-810 [Fix] Correctly run fetch functions

---

js/app/libs.js
js/libs.js

* Removes unnecessary checks for unrelated counts

ID-810 [Feat] Optimise flow and requests for checking updates

---

js/app/libs.js
js/libs.js

ID-810 [Feat] Improve speed and stability of notification updates

---

js/app/libs.js

Ref. https://weboo.atlassian.net/browse/ID-828
I'm not sure why this was added. It could have been by mistake as I was trying out different things.

ID-828 [Fix] Stop clearing notifications

---

interface.html
js/interface.js

Ref. https://weboo.atlassian.net/browse/ID-809

ID-809 [Feat] Adds options for saving notification badge modes

---

js/app/libs.js
js/libs.js

Ref. https://weboo.atlassian.net/browse/ID-797

ID-797 [Feat] Process push payload to mark app notification as read

---

js/app/libs.js
js/build.js
js/build.templates.js
package-lock.json
package.json
templates/notification.build.hbs
templates/toolbar.build.hbs

@romanyosyfiv
OD-626 https://weboo.atlassian.net/browse/OD-626
The date, time, and number of unread notifications that have been localized depend on your browser's language settings.
**ru-RU**
**en-EN**
This change is fully backward compatible.
@upplabs-alex-levchenko

OD-626 [Feature] Localize date, time and number for notifications

---

js/app/libs.js

Ref. https://weboo.atlassian.net/browse/OD-750
Requires https://github.com/Fliplet/fliplet-api/pull/5259

OD-750 [Feat] Enable offline mode to notification inbox

---

js/app/libs.js

Ref. https://weboo.atlassian.net/browse/ID-2192

ID-2192 [Feat] Add support for saveCounts as a public method

---

js/app/libs.js

- ID-2192 [Feat] Add support for saveCounts as a public method #43

Release to Production

---

js/build.templates.js
js/libs.js
translation.json

@romanyosyfiv @inna-bieshulia
OD-818 https://weboo.atlassian.net/browse/OD-818
Fixed translations to the Notification Inbox component
This change is fully backward compatible.
@upplabs-alex-levchenko

OD-818 [Fix] Fixed translation to Notification Inbox

---

js/app/libs.js

Relates to [ID-4427](https://weboo.atlassian.net/browse/ID-4427) and [PR](https://github.com/Fliplet/fliplet-api/pull/6302)
This PR updates session's client source for proper notifications broadcast.
[ID-4427]: https://weboo.atlassian.net/browse/ID-4427?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ID-4427 [Fix] Ensure session client source is updated for each platform for in-app notifications

---

js/app/libs.js

Reverts Fliplet/fliplet-widget-notification-inbox#54 due to QA fail.

Revert "ID-4427 [Fix] Ensure session client source is updated for each platform for in-app notifications"
